version: 0.2
env:
  exported-variables:
    - TF_VERSION
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - "cd /usr/bin"
      - yum install wget unzip
      - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - curl -O https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - unzip ./terraform_${TF_VERSION}_linux_amd64.zip -d /usr/local/bin

  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - terraform init -input=false --backend-config=./env_vars/${TF_ENV}.conf
      - terraform ${TF_ACTION} -input=false -var-file=./env_vars/${TF_ENV}.tfvars -auto-approve

  post_build:
    commands:
      - echo "Terraform completed on `date`"

artifacts:
  files:
    - '**/*'
